[package]
name = "clarity"
version = "0.1.23"
authors = ["Michał Papierski <michal@papierski.net>"]
autotests = true
include = [
    "**/*.rs",
    "Cargo.toml"
]
description = "Lightweight Ethereum client"
repository = "https://github.com/althea-mesh/clarity"
license-file = "LICENSE"
edition     = "2018"


[badges]
travis-ci = { repository = "althea-mesh/clarity", branch = "master" }

[dependencies]
serde = "1.0"
serde-rlp = "0.1"
num-bigint = { version = "0.2", default-features = false, features = ["serde"] }
num-traits = "0.2"
failure = "0.1"
serde_bytes = "0.10"
sha3 = "0.8"
secp256k1 = { version = "0.15", features = ["recovery"] }
lazy_static = "1.4"
serde_derive = "1.0"
num256 = "0.2"
bytecount = "0.6"

[[test]]
name = "transaction_tests"
harness = false

[dev-dependencies]
failure = "0.1"
futures = "0.1"
rand = "0.6"
rustc-test = "0.3.0"
serde_json = "1.0"
web3 = "0.6"
criterion = "0.3"

[[bench]]
name = "crypto_bench"
harness = false
